import { defineCloudflareConfig } from '@opennextjs/cloudflare';

// Static pages and assets are served at the edge; middleware and API routes
// run in the Cloudflare Worker generated by the OpenNext adapter.
export default defineCloudflareConfig();
